version: "3.7"

services:
  squad-member-2:
    build: .
    image: squad-member:1.0
    container_name: mem-2
    ports:
      - 3001:3000
    volumes:
      - ./:/usr/src/app
    networks: 
      - hydra-network

networks:
  hydra-network:
    external:
      name: hydra-network



