version: "3.7"

services: 
  squad-member-1:
    build: .
    image: squad-member:1.0
    container_name: mem-1
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    networks: 
      - hydra-network

networks:
  hydra-network:
    external:
      name: hydra-network






